/**
 * Author:  ilia
 * Created: Dec 16, 2021
 */

CREATE TABLE FINALLAB (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    NAME VARCHAR(255) NOT NULL UNIQUE,
    VAL INTEGER NOT NULL
);

--CREATE INDEX IDX_NAME ON FINALLAB (NAME);
--CREATE INDEX IDX_VAL ON FINALLAB (VAL);